version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: appuser
      RABBITMQ_DEFAULT_PASS: apppass
    depends_on: [keycloak]
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
#    entrypoint: [ "/bin/bash", "-c" ]
#    command: >
#      "/opt/keycloak/bin/kc.sh build --health-enabled=true &&
#       /opt/keycloak/bin/kc.sh start-dev --import-realm"
#       /opt/keycloak/bin/kc.sh start --optimized --import-realm"
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15

  worker:
    build:
      context: .
      dockerfile: Worker/Dockerfile
    depends_on: [ api ]
      #rabbitmq:
      #  condition: service_healthy
      #keycloak:
        #condition: service_healthy
    environment:
      RabbitMq__Host: rabbitmq
      RabbitMq__Username: appuser
      RabbitMq__Password: apppass
      RabbitMq__Queue: source-queue
      RabbitMq__Dlq: source-dlq
      Api__BaseUrl: http://api:8080
      Auth__Authority: http://keycloak:8080/realms/demo
      Auth__ClientId: worker
      Auth__ClientSecret: worker-secret

  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
#      keycloak:
#        condition: service_healthy
    environment:
      RabbitMq__Host: rabbitmq
      RabbitMq__Username: appuser
      RabbitMq__Password: apppass
